title: "My Course Website"
theme: jekyll-theme-minimal
description: >
  Open-source projects, tools, and learning resources that apply business analytics,
  data science, statistics, and programming to real-world problems in industry,
  research, and education.
show_downloads: false

github:
  is_project_page: false

color_mode:
  default: light  # light | dark
  toggle: true
sass:
  style: compressed
